- hosts: all   #localhost   #"{{ ip }}"
  gather_facts: no
  become: yes
  vars:
    mysql_root_password:
    DB_name: zabbix
    DB_user_name: zabbix
    DB_user_password: zabbix
    DB_host_name: localhost

  tasks:

  - name: "タイムゾーン設定"
    timezone:
      name: Asia/Tokyo

  - name: Zabbixリポジトリの追加、SCL有効化
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
      - http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-2-3.el7.centos.noarch.rpm
      - http://mirror.centos.org/altarch/7/extras/aarch64/Packages/centos-release-scl-rh-2-3.el7.centos.noarch.rpm

  - name: zabbix-frontendの有効化
    shell: |
      yum-config-manager --enable zabbix-frontend

  - name: Install Mysql-python
    yum:
      name: "{{ item }}"
    with_items:
      - zabbix-server-mysql
      - zabbix-agent
      - mariadb
      - mariadb-server
      - zabbix-web-japanese.noarch
      - zabbix-web-mysql-scl
      - zabbix-apache-conf-scl
      - MySQL-python

  - name: Start and enable Mariadb
    systemd:
      state: started
      enabled: yes
      name: "{{ item }}"
    with_items:
      - mariadb

  - name: データベース作成
    mysql_db:
      login_unix_socket: /var/lib/mysql/mysql.sock
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: "{{ DB_name }}"
      state: present
      encoding: utf8
      collation: utf8_bin

  - name: データベースのユーザー作成
    mysql_user:
      login_unix_socket: /var/lib/mysql/mysql.sock
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: "{{ DB_user_name }}"
      password: "{{ DB_user_password }}"
      host: "{{ DB_host_name }}"
      priv: '{{ DB_name }}.*:ALL'
      state: present

  - name: Zabbix設定用のSQLを流し込む
    mysql_db:
      name: "{{ DB_name }}"
      state: import
      target: /usr/share/doc/zabbix-server-mysql-5.0.23/create.sql.gz

  - name: Zabbixの設定ファイルのバックアップ
    shell: |
      [ -f /etc/zabbix/zabbix_server.conf.bak ] || cp /etc/zabbix/zabbix_server.conf{,.bak}
      [ -f /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf.bak ] || cp /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf{,.bak}

  - name: /etc/zabbix/zabbix_server.conf書き換え
    lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      backrefs: yes
      state: present
      regexp: '# DBPassword='
      line: 'DBPassword={{ DB_user_password }}'

  - name: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf書き換え
    lineinfile:
      path: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
      state: present
      line: 'php_value[date.timezone] = Asia/Tokyo'

  - name: Start and enable Services
    systemd:
      state: started
      enabled: yes
      name: "{{ item }}"
    with_items:
      - httpd
      - zabbix-agent
      - zabbix-server
      - rh-php72-php-fpm

  - name: Restart Mariadb
    systemd:
      state: started
      name: "{{ item }}"
    with_items:
      - mariadb
