- hosts: all   #localhost   #"{{ ip }}"
  gather_facts: no
  become: yes
  vars:
    Zabbix_ServerIP:   #Zabbix serverIP
  tasks:
  - name:
    yum:
      name:
        - https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        - zabbix-agent
        - zabbix-get

  - name: /etc/zabbix/zabbix_agentd.conf書き換え
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      backup: yes
      backrefs: yes
      state: present
      regexp: '^Server=.*'
      line: 'Server={{ Zabbix_ServerIP }}'

  - name: /etc/zabbix/zabbix_agentd.conf書き換え
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      backrefs: yes
      state: present
      regexp: '^ServerActive=.*'
      line: 'ServerActive={{ Zabbix_ServerIP }}'

  - name: Start and enable zabbix-agent
    systemd:
      state: started
      enabled: yes
      name: zabbix-agent
